name: 📦 Compressed Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  compressed-size:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install

      - uses: actions/checkout@v3
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "./packages/**/dist/**/*.{js,css}"
          build-script: "build:all:es"
          # clean-script: "clean:lock-file"
